import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <header className={styles.header}>
        <h1 className={styles.title}>Ad-To-Gas</h1>
        <div className={styles.button}><ConnectButton showBalance={false} accountStatus="address"/></div>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Bite</a> + <a href="https://google.com">Chatte</a> + 
          <a href="https://nextjs.org">Next.js!</a>
        </h1>

    
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/Krut007/ad-for-gas" rel="noopener noreferrer" target="_blank">
          Build by @Krut007
        </a>
      </footer>
    </div>
  );
};

export default Home;
